#!/bin/sh
#
# This script backups listed important files
#

LIST_FILE="watchlist"
BACKUP_DIR="rootfs"

# Backup $1 which is a file.
backfile() {
    dir=$(dirname $1)
    name=$(basename $1)

    mkdir -p "$BACKUP_DIR/$dir"
    cp $1 "$BACKUP_DIR/$dir/$name"
}

rm -rf $BACKUP_DIR
mkdir -p $BACKUP_DIR

while read -r line
do
    line=${line/#\~/$HOME}
    if [ ! -z "$line" ]; then
	list=$(find "$line" -type f 2> /dev/null)
        if [ -z "$list" ]; then
            echo -e "\033[31m[x] $line \033[0m"
        fi
        for file in $list
        do
            echo -e "\033[32m[\xE2\x9C\x93]\033[0m $file"
            backfile $file
        done
    fi
done < $LIST_FILE

echo "done."
